### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR 

### ISSUE THREAD

**Issue by StarMaster121** [fleischsalatinspace/pathfinder.lost-in-w.space#1]
Trying to connect through any of the posted links, I get ERR_SSL_PROTOCOL_ERROR and cannot connect.

Consistently happening

**Error message**
ERR_SSL_PROTOCOL_ERROR

**Screenshots**

**Client (please complete the following information):**
Desktop/Mobile
Windows
Android

**If reproducible**
I had his happen in 2 locations but both times I was connected through a meshed router system called plume. As soon as I disconnected from that wifi I was able to connect to the site. 

**Expected behavior**
Able to connect
**Additional context**
This is my first post ever on GitHub, but I didn't want it to go unfound. Sorry for the crappy formatting. I was not able to find any information within plumes management portal or resources.

**Comment by StarMaster121** [comment]
I discovered it was the system blocking access to the site but it wasn't throwing the proper error. Was able to correct this on my end within the systems.

**Comment by fleischsalatinspace** [comment]
Sound like some TLS-MitM / capture portal by your wifi router. Glad you could fix it. Closing
