### ISSUE TITLE
403 Forbidden Error

### ISSUE THREAD

**Issue by fgc1701** [fleischsalatinspace/pathfinder.lost-in-w.space#2]
**Describe the issue**
403 Forbidden Error when trying to access https://pathfinder.lost-in-w.space/

**When did the issue arise**
Since this morning, roughly 11am?

**Error message**

403 Forbidden
nginx/1.14.2

**Screenshots**
-

**Client (please complete the following information):**
 - Desktop
 - OS: Windows 
 - Browser Chrome, Firefox, DuckDuckGo

**If reproducible**
1. Go to 'https://pathfinder.lost-in-w.space/'
2. See error

**Comment by fleischsalatinspace** [comment]
Hello,

there was a downtime from 2023-10-01 eve downtime to 2023-10-02 eve downtime with issues already happening on 2023-09-30. Technical details are available here https://forums.eveonline.com/t/service-lost-in-w-space-public-private-pathfinder-hosting/334504/49?u=fleischsalatinspace 

Sorry for inconvience caused
