### ISSUE TITLE
Trouble adding aditional pilots to pathfinder lost in w.space

### ISSUE THREAD

**Issue by StarMapper** [fleischsalatinspace/pathfinder.lost-in-w.space#3]
Basically EvE members have logged into pathfinder lost in space and enable shared access.
There are three people I would like to share a map with.  All have allowed shared access. Only one is easily recognized in the private character to add section.  With the other two the search does not find them when three letters are added to field.
Is there potentially something blocking this from happening?

**Comment by fleischsalatinspace** [comment]
You already wrote the affected characters enabled shared access, but just to double check: they enabled "map invites for private maps" like in the screenshot below? 
![Screenshot_20231205_115315](https://github.com/fleischsalatinspace/pathfinder.lost-in-w.space/assets/76971922/fd5b35db-7993-43e7-946f-719764cb3fa1)

If the issue still persists today, can you please send me the character names and the map name in a direct message on slack? How to join Pathfinder slack is described here https://forums.eveonline.com/t/service-lost-in-w-space-public-private-pathfinder-hosting/334504#contact-6

**Comment by StarMapper** [comment]
The difficulty seems to be amended now. Thank you for the reply. Apparently a phone was used for initial log in and not all the settings may have been visible by mobile.
