### ISSUE TITLE
Pathfinder/lost/in/space

### ISSUE THREAD

**Issue by StarCapsuleer-dotcom** [fleischsalatinspace/pathfinder.lost-in-w.space#4]
When login no issues i do not close out just minimize. When go to after couple minutes get logged out says something about security many times chained and go back and was offline so not counted Wh went to it's really annoying. I do not see why logged out if logged in and never closed why does this do that?

**Comment by fleischsalatinspace** [comment]
Sorry for the late reply. Can you hop onto slack as described here https://forums.eveonline.com/t/service-lost-in-w-space-public-private-pathfinder-hosting/334504#contact-6 and send me time,date and character name when the issue appears?
tyvm. I'll close this issue and if you have anything to add you can reopen it
